import React, { useContext, useEffect } from 'react';
import Head from 'next/head';
import { Context } from '@/provider';
import Button from '@mui/material/Button';
import { Container, ListaLaunches, Table, Tbody, Thead, TheadDiv, TbodyDiv, ButtonsBox } from '../styles/styled';
import YouTubeIcon from '@mui/icons-material/YouTube';
import Pizza from '@/components/grafic';

export default function Home() {
    const { getLauncher, launchers, getRocket, rockets, page, setPage, finalPage,getStatus } = useContext(Context);

    useEffect(() => {
        getLauncher(page); // Fetch initial data based on page
        getRocket();
        getStatus()
    }, []);

    function nextPage() {
        setPage(page + 1);
    }

    function prevPage() {
        if (page > 1) {
            setPage(page - 1);
        }
    }

    useEffect(() => {
        getLauncher(page); // Fetch data based on updated page
    }, [page]);

    return (
        <>
            <Head>
                <title>Diane Almeida</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main style={{display:'flex', flexDirection:'column', justifyContent:'center', alignItems:'center'}}>
                <Pizza/>
                <Container>
                    <ListaLaunches>
                        <Table>
                            <TheadDiv>
                                <Thead>
                                    <tr>
                                        <th>N do Voo</th>
                                        <th>Logo</th>
                                        <th>Missão</th>
                                        <th>Data de Lançamento</th>
                                        <th>Foguete</th>
                                        <th>Resultado</th>
                                        <th>Vídeo</th>
                                    </tr>
                                </Thead>
                            </TheadDiv>
                            <Tbody>
                                {launchers.map((launcher) => (
                                    <tr key={launcher._id}>
                                        <TbodyDiv>
                                            <td>{launcher.flight_number}</td>
                                            <td>
                                                <img
                                                    style={{ maxWidth: '50px' }}
                                                    src={launcher.links.patch.small}
                                                    alt="logo"
                                                />
                                            </td>
                                        </TbodyDiv>
                                        <TbodyDiv>
                                            <td>{launcher.name}</td>
                                            <td>
                                                {(() => {
                                                    const data = new Date(launcher.date_utc);
                                                    const dia = data.getUTCDate().toString().padStart(2, '0');
                                                    const mes = (data.getUTCMonth() + 1).toString().padStart(2, '0');
                                                    const ano = data.getUTCFullYear();
                                                    const data_formatada = `${dia}/${mes}/${ano}`;
                                                    return data_formatada;
                                                })()}
                                            </td>
                                        </TbodyDiv>
                                        <TbodyDiv>
                                            <td>
                                                {rockets.map((rocket) => {
                                                    if (rocket.id === launcher.rocket) {
                                                        return rocket.name;
                                                    }
                                                    return null;
                                                })}
                                            </td>
                                            <td>
                                                {
                                                    (() => {
                                                        return launcher.success ? (
                                                            <span style={{ backgroundColor: "#17a362", padding: "0.2em 0.5em", borderRadius: "4px", color: "#FFF", height: 20, width: '100px' }}>
                                                                Sucesso
                                                            </span>
                                                        ) : (
                                                            <span style={{ backgroundColor: "#660517", padding: "0.2em 0.5em", borderRadius: "4px", color: "#FFF", height: 20, width: '100px' }}>
                                                                Falha
                                                            </span>
                                                        );
                                                    })()
                                                }
                                            </td>
                                        </TbodyDiv>
                                        <TbodyDiv style={{ maxWidth: '100px' }}>
                                            <td>
                                                <a href={launcher.links.webcast} target='blank'>
                                                    <YouTubeIcon style={{ color: 'red' }} />
                                                </a>
                                            </td>
                                        </TbodyDiv>

                                    </tr>
                                ))}
                            </Tbody>
                            <ButtonsBox>
                                <Button
                                    style={{
                                        width: '150px',
                                        marginBottom: '10px'
                                    }}
                                    disabled={page <= 1}
                                    onClick={prevPage}
                                    variant="outlined">
                                    Anterior
                                </Button>
                                <Button
                                    style={{
                                        width: '150px',
                                        marginBottom: '10px'
                                    }}
                                    onClick={nextPage}
                                    disabled={page >= finalPage}
                                    variant="outlined">
                                    Próxima
                                </Button>
                            </ButtonsBox>
                        </Table>
                    </ListaLaunches>
                </Container>
            </main>
        </>
    );
}
