import React, { useContext, useEffect } from 'react'; // Import React and its hooks
import Head from 'next/head';
import { Context } from '@/provider';
import { Container, ListaLaunches, Table, Tbody, Thead, TheadDiv, TbodyDiv } from './styled';

export default function Home() {
    const { getLauncher, launchers, getRocket, rockets } = useContext(Context); // Destructure getLauncher and launchers from context

    useEffect(() => {
        getLauncher();
        getRocket();
    }, []);

    console.log('launcher', launchers);
    console.log('rocket', rockets)

    return (
        <>
            <Head>
                <title>Diane Almeida</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Container>
                    <ListaLaunches>
                        <Table> {/* Use the Table component */}
                            <TheadDiv>
                                <Thead>
                                    <tr>
                                        <th>N do Voo</th>
                                        <th>Logo</th>
                                        <th>Missão</th>
                                        <th>Data de Lançamento</th>
                                        <th>Foguete</th>
                                        <th>Resultado</th>
                                        <th>Vídeo</th>
                                    </tr>
                                </Thead>
                            </TheadDiv>
                            <Tbody>
                                {launchers.map((launcher) => (
                                    <tr key={launcher._id}>
                                        <TbodyDiv>
                                            <td>{launcher.flight_number}</td>
                                            <td>
                                                <img
                                                    style={{ maxWidth: '50px' }}
                                                    src={launcher.links.patch.small}
                                                    alt="logo"
                                                />
                                            </td>
                                        </TbodyDiv>
                                        <TbodyDiv>
                                            <td>{launcher.name}</td>
                                            <td>
                                                {(() => {
                                                    const data = new Date(launcher.date_utc);
                                                    const dia = data.getUTCDate().toString().padStart(2, '0');
                                                    const mes = (data.getUTCMonth() + 1).toString().padStart(2, '0');
                                                    const ano = data.getUTCFullYear();
                                                    const data_formatada = `${dia}/${mes}/${ano}`;
                                                    return data_formatada;
                                                })()}
                                            </td>
                                        </TbodyDiv>
                                        <TbodyDiv>
                                            <td>
                                                {rockets.map((rocket) => {
                                                    if (rocket.id === launcher.rocket) {
                                                        return rocket.name;
                                                    }
                                                    return null;
                                                })}
                                            </td>
                                            <td>
                                                {
                                                    (() => {
                                                        return launcher.success ? (
                                                            <span style={{ backgroundColor: "#17a362", padding: "0.2em 0.5em", borderRadius: "4px", color: "#FFF", height: 20 }}>
                                                                Sucesso
                                                            </span>
                                                        ) : (
                                                            <span style={{ backgroundColor: "#da4a64", padding: "0.2em 0.5em", borderRadius: "4px", color: "#FFF", height: 20 }}>
                                                                Falha
                                                            </span>
                                                        );
                                                    })()
                                                }
                                            </td>
                                        </TbodyDiv>
                                        <TbodyDiv>
                                            <td>
                                                <a href={launcher.links.webcast} target='blank'>
                                                    <img src='../img/youtube.png' alt='youtube' />
                                                </a>
                                            </td>
                                        </TbodyDiv>
                                        <TbodyDiv> teste</TbodyDiv>
                                    </tr>
                                ))}
                            </Tbody>
                        </Table>
                    </ListaLaunches>
                </Container>
            </main>
        </>
    );
}
